apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggingapp-deployment
spec:
  selector:
    matchLabels:
      app: bloggingapp
  replicas: 1
  template:
    metadata:
      labels:
        app: bloggingapp
    spec:
      containers:
        - name: bloggingapp
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred # Reference to the Docker registry secret
        
---


apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: mayur2:/Service:guestbook/bloggingappsvc
  name: bloggingappsvc
  namespace: guestbook
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: bloggingapp
  type: LoadBalancer

